#!/usr/bin/env python

__author__ = "Kevin D. Smith <Kevin.Smith@sixquickrun.com>"
__revision__ = "$Revision$"
__scid__ = "$Id$"

import os, glob

for i, png in enumerate(glob.glob('Icons/*.png')):
    name = os.path.splitext(os.path.basename(png))[0].replace('-', ' ').title().replace(' ','')
    if i == 0:
        os.system('img2py -n %s %s FileIcons.py' % (name, png))
    else:
        os.system('img2py -a -n %s %s FileIcons.py' % (name, png))
