#!/usr/bin/env python

import os, glob

for i, png in enumerate(glob.glob('Icons/*.png')):
    name = os.path.splitext(png)[0].replace('-', ' ').title().replace(' ','')
    if i == 0:
        os.system('img2py -n %s %s FileIcons.py' % (name, png))
    else:
        os.system('img2py -a -n %s %s FileIcons.py' % (name, png))
